spring.application.name=mynewapp
server.port=${PORT:8080}
server.servlet.context-path=/mynewapp
spring.main.allow-bean-definition-overriding=true
spring.mongodb.uri=mongodb+srv://uddiptagogo_db_user:F7wY35r5mAjPKLRh@livescoreboard.apxr8fo.mongodb.net/mymongodb?appName=LiveScoreBoard
#spring.mongodb.uri=mongodb://localhost:27017/mymongodb

#spring.mongodb.uri=mongodb://localhost:27017/mymongodb
#spring.data.mongodb.uri=${MONGODB_URI}