spring.application.name=mynewapp
server.port=${PORT:8080}
server.servlet.context-path=/mynewapp
spring.main.allow-bean-definition-overriding=true
spring.mongodb.uri=${MONGODB_URI}
#spring.mongodb.uri=mongodb://localhost:27017/mymongodb

#spring.mongodb.uri=mongodb://localhost:27017/mymongodb
#spring.data.mongodb.uri=${MONGODB_URI}